const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {RaceService}=require('../backend/race-service.cjs');
const root=path.resolve(__dirname,'../dist');
const pause=()=>new Promise(r=>setTimeout(r,25));
async function until(fn){for(let i=0;i<80;i++){if(fn())return;await pause();}assert.fail('UI state did not settle');}
async function page(t,svc,stream=false){const {Window}=await import('happy-dom');const w=new Window({url:'http://localhost:5173',settings:{enableJavaScriptEvaluation:true,suppressInsecureJavaScriptEnvironmentWarning:true,disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});t.after(()=>w.happyDOM.close());w.document.body.innerHTML=fs.readFileSync(path.join(root,'index.html'),'utf8').match(/<body>([\s\S]*?)<\/body>/)[1].replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,'');w.Audio=class{constructor(src){this.src=src;}play(){return Promise.resolve();}pause(){}};w.requestAnimationFrame=()=>0;w.Element.prototype.animate=()=>({cancel(){}});w.DOMPoint=class{constructor(x,y){this.x=x;this.y=y;}matrixTransform(){return this;}};
 w.requests=[];w.fakeSockets=[];
 if(stream)w.WebSocket=class {constructor(url,protocols){this.url=url;this.protocols=protocols;this.readyState=0;w.fakeSockets.push(this);w.setTimeout(()=>{this.readyState=1;this.onopen?.();},0);}push(){if(this.readyState===1)this.onmessage?.({data:JSON.stringify({type:'state',state:svc.state(w.user)})});}send(){this.push();}close(){this.readyState=3;this.onclose?.();}};
 w.fetch=async(url,opts={})=>{const p=new URL(url,'http://localhost:5173'),op=p.pathname.slice(5),data=opts.body?JSON.parse(opts.body):{},token=opts.headers?.Authorization?.replace('Bearer ','');let result;w.requests.push(op);try{if(op==='session'){result={...svc.session(token),websocket:stream};w.user=svc.auth(result.token);}else{const u=svc.auth(token);if(op==='state')result=svc.state(u);else if(op==='solo'||op==='create')result=svc.create(u,data,op==='solo');else if(op==='join')result=svc.join(u,data.code);else if(op==='loaded')result=svc.loaded(u,data.round);else if(op==='submit')result=svc.submit(u,data);else if(op==='nickname'){svc.nickname(u,data.nickname);result={nickname:data.nickname};}else if(op==='leaderboard'||op==='history')result=svc.results(u,p.searchParams.get('game'),p.searchParams.get('mode'),op==='history');else if(op==='start')result=svc.start(u);else result=svc[op](u,data);}return {ok:true,json:async()=>JSON.parse(JSON.stringify(result))};}catch(e){return {ok:false,json:async()=>({error:e.message})};}};
 for(const file of ['audio.js','repair-core.js','repair-levels.js','custom-core.js','custom-ui.js','repair.js','salvage-core.js','salvage-levels.js','salvage-3d.js','salvage-custom-core.js','salvage-custom-ui.js','salvage.js','race-config.js','race.js','app.js'])w.eval(fs.readFileSync(path.join(root,file),'utf8'));
 for(const name of ['RepairGame','SalvageGame']){const start=w[name].startRace;w[name].startRace=(l,cb)=>{w.raceCallback=cb;w.raceLevel=l;return start(l,cb);};}
 return w;
}
const click=(w,a)=>{const b=w.document.querySelector('#race-app [data-act="'+a+'"]');assert(b,'button '+a);b.click();};
for(const game of ['repair','salvage'])test(`${game}: first card, solo countdown, five rounds, editable nickname, review and return`,async t=>{
 let now=Date.now();const svc=new RaceService({now:()=>now}),w=await page(t,svc);w.document.querySelector('[data-module="'+game+'"]').click();const first=w.document.querySelector((game==='repair'?'#repair-app':'#salvage-app')+' .level-grid').firstElementChild;assert.match(first.textContent,/竞速挑战/);first.click();await until(()=>w.user);w.document.querySelector('#race-name').value='同名管理员';click(w,'solo');await until(()=>w.raceLevel&&svc.current(w.user).readyAt);const r=svc.current(w.user);assert.equal(r.players[0].nickname,'同名管理员');assert.equal(w.document.querySelector('.race-curtain').hidden,false);assert(w.document.querySelector('.race-countdown-panel'));assert.doesNotMatch(w.document.querySelector('.race-curtain').textContent,/双方|对方/);
 for(let i=0;i<5;i++){await until(()=>r.readyAt!==null&&w.raceLevel.id.endsWith('-'+i));now+=i===0?5000:1000;await new Promise(r=>setTimeout(r,420));w.raceCallback.onComplete(JSON.parse(JSON.stringify(r.bank[i].answer)));await until(()=>w.document.querySelector('.race-complete.is-own'));assert.match(w.document.querySelector('.race-complete').textContent,game==='repair'?/修复完成/:/回收成功/);assert(w.raceLevel.id.endsWith('-'+i));assert.equal(w.document.querySelector(game==='repair'?'#repair-app':'#salvage-app').inert,true);await until(()=>r.status==='ended'||r.round===i+1);}
 await until(()=>w.document.querySelector('[data-act="review"]'));assert.match(w.document.querySelector('#race-app').textContent,/挑战完成/);assert.equal(svc.records.length,1);click(w,'review');await until(()=>w.document.querySelectorAll('.race-answer').length===5);assert.equal(w.document.querySelectorAll('.race-answer textarea').length,5);click(w,'back');await until(()=>w.document.querySelector('[data-act="review"]'));assert.equal(svc.current(w.user).status,'ended');click(w,'back');await until(()=>w.document.querySelector('#race-name'));assert.equal(w.document.querySelector('.terminal').inert,true);for(const action of ['history','leaderboard']){click(w,action);await until(()=>w.document.querySelectorAll('.race-history-previews .race-answer-grid').length===5);assert.equal(w.document.querySelectorAll('#race-app textarea').length,0);const copy=w.document.querySelector('[data-copy-text]');assert.equal(copy.dataset.copyText,svc.records[0].seeds[0]);copy.click();await until(()=>copy.textContent==='已复制');assert.equal(await w.navigator.clipboard.readText(),svc.records[0].seeds[0]);click(w,'back');}click(w,'back');assert.equal(w.document.querySelector('#race-app').hidden,true);
});
test('two browser clients synchronize rounds and host rematch without stale result',async t=>{
 let now=Date.now();const svc=new RaceService({now:()=>now}),a=await page(t,svc),b=await page(t,svc);a.RaceChallenge.open('salvage');b.RaceChallenge.open('salvage');await until(()=>a.user&&b.user);click(a,'create');await until(()=>a.user.active);const r=svc.current(a.user);b.document.querySelector('#race-code').value=r.code;click(b,'join');await until(()=>r.players.length===2);await new Promise(r=>setTimeout(r,420));click(a,'start');await until(()=>r.readyAt&&b.raceLevel);
 for(let i=0;i<3;i++){await until(()=>r.readyAt&&a.raceLevel.id===b.raceLevel.id&&a.raceLevel.id.endsWith('-'+i));now+=5000;await new Promise(r=>setTimeout(r,420));a.raceCallback.onComplete(JSON.parse(JSON.stringify(r.bank[i].answer)));await until(()=>a.document.querySelector('.race-complete.is-own')&&b.document.querySelector('.race-complete.is-opponent'));assert.match(b.document.querySelector('.race-complete').textContent,/对方已完成/);assert(a.raceLevel.id.endsWith('-'+i));await until(()=>r.status==='ended'||r.round===i+1);}
 await until(()=>a.document.querySelector('[data-act="review"]')&&b.document.querySelector('[data-act="review"]'));const old=a.raceLevel.id;click(a,'start');await until(()=>a.raceLevel.id!==old&&a.raceLevel.id===b.raceLevel.id);assert.equal(r.round,0);assert.deepEqual(r.players.map(p=>p.score),[0,0]);
});


test('WebSocket client uses push instead of polling and reconnects without exposing token in URL',async t=>{
 const svc=new RaceService(),w=await page(t,svc,true);w.RaceChallenge.open('salvage');await until(()=>w.user);click(w,'create');await until(()=>w.fakeSockets[0]?.readyState===1);const ws=w.fakeSockets[0];assert.equal(new URL(ws.url).pathname,'/api/stream');assert.equal(new URL(ws.url).search,'');assert(ws.protocols.some(p=>p.startsWith('auth.')));
 const before=w.requests.filter(p=>p==='state').length;await new Promise(r=>setTimeout(r,800));assert.equal(w.requests.filter(p=>p==='state').length,before);
 const guest=svc.auth(svc.session().token);svc.join(guest,svc.current(w.user).code);ws.push();assert.equal(w.document.querySelectorAll('.race-players div').length,2);
 ws.close();await until(()=>w.fakeSockets.length===2&&w.fakeSockets[1].readyState===1);assert.equal(w.document.querySelectorAll('.race-players div').length,2);
 click(w,'leave');await until(()=>w.document.querySelector('#race-name'));assert.equal(w.fakeSockets[1].readyState,3);
});
